### ISSUE TITLE
Add a way to end a blind mode game and reveal all items on the card

### ISSUE THREAD

**Issue by bl4ckscor3** [NeunEinser/bingo#185] opened 2023-08-06 14:31 UTC
This could be useful for players who don't want to play a blind mode game until all items are collected, and are interested in seeing the remaining items on the card.

**Comment by NeunEinser** [comment] 2023-08-06 21:29
Duplicate of #182 (closed as it's implemented for next version)

**Closed by NeunEinser** 2023-08-06 21:29 UTC
Labels: duplicate
